//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.03.12 at 06:41:12 PM EET 
//


package tr.edu.boun.cmpe.scn.api.message;

import java.util.ArrayList;
import java.util.List;


public class Arguments {

    protected List<Argument> argument;

    /**
     * Gets the value of the argument property.
     * <p>
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the argument property.
     * <p>
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getArgument().add(newItem);
     * </pre>
     * <p>
     * <p>
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Argument }
     */
    public List<Argument> getArgument() {
        if (argument == null) {
            argument = new ArrayList<Argument>();
        }
        return this.argument;
    }

}
