//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.03.12 at 06:41:12 PM EET 
//


package tr.edu.boun.cmpe.scn.api.message;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the tr.edu.boun.cmpe.scn.api.message package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: tr.edu.boun.cmpe.scn.api.message
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link ServiceUp }
     * 
     */
    public ServiceUp createServiceUp() {
        return new ServiceUp();
    }

    /**
     * Create an instance of {@link ServiceProbe }
     * 
     */
    public ServiceProbe createServiceProbe() {
        return new ServiceProbe();
    }

    /**
     * Create an instance of {@link ServiceInterest }
     * 
     */
    public ServiceInterest createServiceInterest() {
        return new ServiceInterest();
    }

    /**
     * Create an instance of {@link ServiceData }
     * 
     */
    public ServiceData createServiceData() {
        return new ServiceData();
    }

    /**
     * Create an instance of {@link Arguments }
     * 
     */
    public Arguments createArguments() {
        return new Arguments();
    }

    /**
     * Create an instance of {@link Argument }
     * 
     */
    public Argument createArgument() {
        return new Argument();
    }

    /**
     * Create an instance of {@link ScnMessage }
     * 
     */
    public ScnMessage createScnMessage() {
        return new ScnMessage();
    }

}
