//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.03.12 at 06:41:12 PM EET 
//


package tr.edu.boun.cmpe.scn.api.message;

import com.fasterxml.jackson.databind.ObjectMapper;
import org.onlab.packet.BasePacket;
import org.onlab.packet.IPacket;
import tr.edu.boun.cmpe.scn.api.common.Constants;

import java.nio.ByteBuffer;

public class ScnMessage extends BasePacket {

    protected int messageTypeId;
    protected String serviceName;

    /**
     * Gets the value of the messageTypeId property.
     */
    public int getMessageTypeId() {
        return messageTypeId;
    }

    /**
     * Sets the value of the messageTypeId property.
     */
    public void setMessageTypeId(int value) {
        this.messageTypeId = value;
    }

    /**
     * Gets the value of the serviceName property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getServiceName() {
        return serviceName;
    }

    /**
     * Sets the value of the serviceName property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setServiceName(String value) {
        this.serviceName = value;
    }


    public byte[] serialize() {
        throw new IllegalStateException("Serialization is not supported");
    }

    @Override
    public IPacket deserialize(final byte[] data, final int offset,
                               final int length) {
        final ByteBuffer bb = ByteBuffer.wrap(data, offset, length);
        try {
            String received = new String(bb.array(), Constants.UTF8);
            ObjectMapper mapper = new ObjectMapper();
            return mapper.readValue(received.trim(), this.getClass());
        } catch (java.io.IOException e) {
            System.err.println("Unable to deserialize the packet " + this.getClass());
            e.printStackTrace();
        }
        return null;
    }

}
