//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.03.12 at 06:41:12 PM EET 
//


package tr.edu.boun.cmpe.scn.api.message;

import tr.edu.boun.cmpe.scn.api.common.ScnBasePacket;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for ScnMessage complex type.
 * <p>
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;complexType name="ScnMessage"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="messageTypeId" type="{}MessageType"/&gt;
 *         &lt;element name="serviceName" type="{}ServiceName"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ScnMessage", propOrder = {
        "messageTypeId",
        "serviceName"
})
@XmlSeeAlso({
        ServiceUp.class,
        ServiceProbe.class,
        ServiceInterest.class,
        ServiceData.class
})
public class ScnMessage extends ScnBasePacket {

    protected int messageTypeId;
    @XmlElement(required = true)
    protected String serviceName;

    /**
     * Gets the value of the messageTypeId property.
     */
    public int getMessageTypeId() {
        return messageTypeId;
    }

    /**
     * Sets the value of the messageTypeId property.
     */
    public void setMessageTypeId(int value) {
        this.messageTypeId = value;
    }

    /**
     * Gets the value of the serviceName property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getServiceName() {
        return serviceName;
    }

    /**
     * Sets the value of the serviceName property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setServiceName(String value) {
        this.serviceName = value;
    }

}
