//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.03.12 at 06:41:12 PM EET 
//


package tr.edu.boun.cmpe.scn.api.message;

import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.core.JsonProcessingException;
import com.fasterxml.jackson.databind.ObjectMapper;
import tr.edu.boun.cmpe.scn.api.common.Constants;
import tr.edu.boun.cmpe.scn.api.common.ScnMessageType;

import java.io.UnsupportedEncodingException;

public class ServiceData extends ScnMessage {

    protected String messageId;


    /**
     * Gets the value of the messageId property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getMessageId() {
        return messageId;
    }

    /**
     * Sets the value of the messageId property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setMessageId(String value) {
        this.messageId = value;
    }

    @Override
    public byte[] serialize() {
        byte[] payload = null;
        ObjectMapper mapper = new ObjectMapper();
        try {
            payload = mapper.writeValueAsString(copy()).getBytes(Constants.UTF8);
        } catch (UnsupportedEncodingException | JsonProcessingException e) {
            System.err.println("Unable to serialize the packet " + this.getClass());
            e.printStackTrace();
        }
        return payload == null ? new byte[0] : payload;
    }

    private ServiceData copy() {
        ServiceData msg = new ServiceData();
        msg.setServiceName(serviceName);
        msg.setMessageTypeId(messageTypeId);
        msg.setMessageId(messageId);
        return msg;
    }
}
