//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.03.12 at 06:41:12 PM EET 
//


package tr.edu.boun.cmpe.scn.api.message;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for ServiceUp complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ServiceUp"&gt;
 *   &lt;complexContent&gt;
 *     &lt;extension base="{}ScnMessage"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="servicePort" type="{http://www.w3.org/2001/XMLSchema}int"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/extension&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ServiceUp", propOrder = {
    "servicePort"
})
public class ServiceUp
    extends ScnMessage
{

    protected int servicePort;

    /**
     * Gets the value of the servicePort property.
     * 
     */
    public int getServicePort() {
        return servicePort;
    }

    /**
     * Sets the value of the servicePort property.
     * 
     */
    public void setServicePort(int value) {
        this.servicePort = value;
    }

}
